{
	"data": "ENC[AES256_GCM,data:aoK8IChYkgZb/PhlsjcpmnTuFuAbGtg57NqSGZzVhQ/0skwYqFkUIiFfqo5iq6XhXQ7QpVOkfLwf9YMMErd+QlNzumzZOlrK0YWOaqqbDqUl/0q51ijMnDyjFbUmyH1hwteWtbEv+HdJ8YWWLGsw6zEh2fMtxmAZ/JHV4OdijeI=,iv:IM6fdHFGLAlvxcw6awSg/a3L6CxiDCjsUnzuBIsSwRU=,tag:V6GAEKTno05SUEUzsAyeBw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNGxJcHFmL2Fmcm5HQ25i\nc0lacXVwMDhRaFhMV3Y0U01mQ251SnAvY25JCmpJZGJkZG1WSTdTV05vRXBkdGEr\nTkdwRDlDcWNLREh0N0JuWERxQnZRbWcKLS0tIHF2ck1ndmpGaGNBZjRJUExiTnNC\nRS82WGRaWXlnUmI0cVQ2YUgzSFV4RVEKn55FKO/s8zDqeatc/65wjmGCIvBzDTV3\nLduZ8pqW0y3f1Axm/2BpuubrUQooqlyN5TIKr6+8LSRq88NxvyuDPw==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age199ugvy7yhelyqgszu4adsj8r9kdymnsdermy523f7rhlatqf4d9szlgdm5"
			}
		],
		"lastmodified": "2026-07-08T06:34:28Z",
		"mac": "ENC[AES256_GCM,data:tmhsYZI4ndrFJFY3G3B6ycG/3hjFe7Sz88KMi6701Hutk6svgFPPpOrNmGA21IahnsgGP3zIaTbplcTmhjQScknews0mN/wG0LM0neY74zz5kAv2jIixK3bS92oJtdIqkryOaYlIZ5JzQjv4mXEk1Tp4EmJq4M7qaIHzDv030lA=,iv:cyI9VsHP7h9PhBUyotVL2ygOAz0JGzOGYRjL4hXlx4g=,tag:AP5xJWJSrDHU60tuOFSCng==,type:str]",
		"version": "3.13.1"
	}
}
