{
	"data": "ENC[AES256_GCM,data:grTg/YJH7EeNQhZQ7/nlIZlYiW16x8qzf3cVy3VjnpwuUEGEOpHa8VWpzEaOnOARGo38/WwmNo56cZR/Z6+JANkwVP9F4ezEcggTGY+mIEunqS9LnZ2nCYzmftAwyNAqLLj+4PnrQYl6jvFUMceF,iv:NKrMfXRpsTR7e5ed0pY1aEGhh98g6AQYNCjTq8Hl8us=,tag:AX91UcAwYf5GWtlXkTLHqw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNGxJcHFmL2Fmcm5HQ25i\nc0lacXVwMDhRaFhMV3Y0U01mQ251SnAvY25JCmpJZGJkZG1WSTdTV05vRXBkdGEr\nTkdwRDlDcWNLREh0N0JuWERxQnZRbWcKLS0tIHF2ck1ndmpGaGNBZjRJUExiTnNC\nRS82WGRaWXlnUmI0cVQ2YUgzSFV4RVEKn55FKO/s8zDqeatc/65wjmGCIvBzDTV3\nLduZ8pqW0y3f1Axm/2BpuubrUQooqlyN5TIKr6+8LSRq88NxvyuDPw==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age199ugvy7yhelyqgszu4adsj8r9kdymnsdermy523f7rhlatqf4d9szlgdm5"
			}
		],
		"lastmodified": "2026-07-08T06:47:20Z",
		"mac": "ENC[AES256_GCM,data:mWVhHfgW0jEnbrAKUWnu9Uvk3EZMlSDPbA/taGbGXFjJmB7/x4K+BdZosKUsfe+K9eFfG+rNovY6Hw0irgkj75qO3j8kJVlCkeggk6C+AEhfMAicdiIQ6ZsOmCS5M7uVOwJP8WE5+ZrHkCMuAeFm1uvMo47beqA02V4oTZVhw/8=,iv:eLrgNhB9gC42or6ZkB+brSVhozxraQHAmj7pMRpngyE=,tag:9zxz8rw19ryKkZSSCTv4RA==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.1"
	}
}
